language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: fJrIyde4VGLJxtCKjfBOrnsV1HFtB2egq/aQ/hXvu9TPWj84fxrYFvgEMmgmc6zK03qkT4chwM3zQ1qQ4d7y5aULSVdwpfHpwmRQgFCyW5FgqIG1Nrqqj4j+2sthS76dIN3ZGdLAMmnaYh969mHEoYEurPn6faKHznKkX4RDc38=
  - secure: lZKEIdypC8gQNRt/+iZpt85+EZ+U0hYeXoiHuncf6zp5QHy48/DvmEOz0oKm7aDtSF1l6BAv0+lhODckJ64ngP0Dpg7wcrjU6Q3MAT5eRYWQNPeRpWKzpQtvooUwvTx6vh6sukBGM4AX66jmcgCd3B8fvJHSMgX7YF6ifkiedOk=
  - secure: UhQpfR4Y8h8qQunkFpeYhyCXwtUjaQgOHLajertiLtC/YdhpuAwLcOuEpg13KM+Fnw9CaYkwJ2CRnfD6JZbq6UT4PMcG+iHac5fqU82MOG4z2SSG3cirg5WAd41BykhS8e+fTHpygQy2hMYSC+zLiMdiOZ36d0JCqMS4WF2q9Lc=
notifications:
  slack:
    secure: lVhziZ6BuJz9ArWjcdde1Ztuy+KXpR7i7urpih7a3hMhDnHIouWnSLk5ZJ4Xnf5DZ8rxBHhSC1oZdzRCD5GeyCV+kiYRYCBjD4zaaeq8niEYLCjj52h3NR6zn5/TAh3xe8lzOl8g8RoZhKRY4ziQA1Z0WKJUYqo9QlBZNQ5YHss=
