language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: qE5Y17UtXJK9jiX/Gm0vGpmXnNSWxXWY3ZZx1rVqhEJcGf5QM8GLfmHn9ISpn6cBX/lt7lfR5kGvSYbbTrX1CwnhMIQn1P9Ff6/knOskiO3XetZMU4PNzDk/9OfdZPbPacBAJCVn5hAGtMePzWpjuU0oR/1yR2CNATIJQk0tkuM=
  - secure: Ko+jq2mq73YQYdARbyamERStqohU9lzYp3R0QNjzmHox56NDc6HBQL73JTJWV0XN5dbh7P2zaUrXFbWHoYvhUMJl3ggAfibnJc1ylL+2E+vBkKE/CIrZ/1k/MMi5lmJf/BPGijJtWxH+T15/1O3MZhCK/eCqKcYlDkjrK4Hl0H4=
  - secure: qNAu0Ln1mPfVTWrngpsPcLdPWZCQiOebvHii1nW86TbSFmzZ06WGFA6wRRba7b+xbB1sM7Jlb1V3Xgxdnx/rgLNLe2rYvhk8mtgx6vXGlOPWHmI2fVgRN1rYkiUO/clKQhc4SoxNGRv1D84N6XUM9qDiyEzRNYkiewRWgRlg+F8=
notifications:
  slack:
    secure: NseKN+aeRhm9EVBsnjrvZxqsRXyHMTaASuXWfDE7T/OPHLvZx7i49nGrE48rxQvZjabeWjtwmOyIBOfWOVFfPJZZD7icThJZGzqm1PsOVJqWgZI7lXDIb4HUFFo351aLSdLnQlqJM3crDo+KCt0ilJmDvFDK+NAiEYGBaA67GnU=
